/* Generated by cbindgen. Do not edit by hand. */

#ifndef TYPECLAW_H
#define TYPECLAW_H

#include <stdint.h>
#include <stddef.h>

#define TC_EVENT_LETTER 0

#define TC_EVENT_BACKSPACE 1

#define TC_EVENT_END_TOKEN 2

#define TC_EVENT_LITERAL 3

#define TC_MOD_SHIFT 1

#define TC_MOD_CONTROL 2

#define TC_MOD_OPTION 4

#define TC_MOD_COMMAND 8

#define TC_CONTEXT_SECURE_INPUT 1

#define TC_CONTEXT_AUTOMATIC_PROCESSING_DISABLED 2

#define TC_CONTEXT_AUTOMATIC_SWITCHING_DISABLED 4

#define TC_HOST_POLICY_SECURE_INPUT 1

#define TC_HOST_POLICY_AUTOMATIC_PROCESSING_DISABLED 2

#define TC_HOST_POLICY_MANUAL_SWITCH_DISABLED 4

#define TC_HOST_POLICY_TERMINAL_SURFACE 8

#define TC_HOST_POLICY_REASON_NORMAL 0

#define TC_HOST_POLICY_REASON_SECURE_INPUT 1

#define TC_HOST_POLICY_REASON_TERMINAL_BUNDLE 2

#define TC_HOST_POLICY_REASON_TERMINAL_SURFACE 3

#define TC_HOST_POLICY_REASON_DISABLED_BUNDLE 4

#define TC_HOST_POLICY_REASON_AUTOMATIC_PROCESSING_DISABLED_BUNDLE 5

#define TC_HOST_POLICY_REASON_UNAVAILABLE_HOST_CONFIG 255

#define TC_OBSERVATION_NONE 0

#define TC_OBSERVATION_SWITCH_FUTURE_LAYOUT 1

#define TC_OBSERVATION_RESET_TOKEN 2

#define TC_LAYOUT_ENGLISH 0

#define TC_LAYOUT_SECONDARY 1

typedef struct TcEngine TcEngine;

typedef struct TcHostConfig TcHostConfig;

typedef struct {
    size_t min_token_len;
    size_t max_token_len;
    float confidence_margin;
    float dict_exact_weight;
    float dict_prefix_weight;
    float ngram_only_confidence_margin;
    float bigram_weight;
    float trigram_weight;
    uint8_t length_normalize;
    uint8_t disable_on_internal_caps;
} TcEngineConfig;

typedef struct {
    uint8_t secure_input;
    const char *bundle_id_utf8;
    const char *application_name_utf8;
    const char *input_client_class_utf8;
    const char *focused_element_role_utf8;
    const char *focused_element_subrole_utf8;
    const char *focused_element_role_description_utf8;
    const char *focused_element_identifier_utf8;
    const char *focused_element_description_utf8;
    const char *focused_element_context_utf8;
    const char *focused_window_title_utf8;
} TcHostSurfaceFacts;

typedef struct {
    uint32_t flags;
    uint8_t reason;
} TcHostInputPolicy;

typedef struct {
    uint8_t tag;
    uint8_t layout;
} TcObservation;

typedef struct {
    uint8_t tag;
    uint8_t physical;
    uint8_t modifiers;
    uint32_t codepoint;
} TcEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *typeclaw_last_error_message(void);

/**
 * Allocates a new engine using the language bundle embedded into the library.
 *
 * This is the normal constructor for release builds and the macOS observer agent.
 * Returns null if the embedded bundle fails to deserialize.
 */
TcEngine *typeclaw_engine_new_embedded(void);

/**
 * Allocates a new embedded engine with explicit runtime tuning.
 *
 * Returns null if the embedded bundle fails to deserialize or the config contains
 * invalid numeric values.
 */
TcEngine *typeclaw_engine_new_embedded_with_config(TcEngineConfig config);

/**
 * Allocates a new engine, loading the language bundle from the directory at `data_dir_utf8`.
 * `data_dir_utf8` must point to a NUL-terminated UTF-8 path. Returns null on failure.
 *
 * # Safety
 *
 * `data_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TcEngine *typeclaw_engine_new_from_data_dir(const char *data_dir_utf8);

/**
 * Allocates a new engine from `data_dir_utf8` with explicit runtime tuning.
 *
 * Returns null if path decoding, data loading, or config validation fails.
 *
 * # Safety
 *
 * `data_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TcEngine *typeclaw_engine_new_from_data_dir_with_config(const char *data_dir_utf8,
                                                        TcEngineConfig config);

/**
 * Allocates a new engine using embedded English plus the secondary pack in `pack_dir_utf8`.
 * The pack directory must contain `pack.toml`, `ngrams.bin`, and `dict.fst`.
 *
 * # Safety
 *
 * `pack_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TcEngine *typeclaw_engine_new_from_pack_dir(const char *pack_dir_utf8);

/**
 * Allocates a new engine from `pack_dir_utf8` with explicit runtime tuning.
 *
 * Returns null if path decoding, pack loading, or config validation fails.
 *
 * # Safety
 *
 * `pack_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TcEngine *typeclaw_engine_new_from_pack_dir_with_config(const char *pack_dir_utf8,
                                                        TcEngineConfig config);

/**
 * Allocates a new engine from a resolved host config.
 *
 * Rust owns the engine-source decision: data directory wins, embedded
 * Ukrainian is used for `secondary = "uk"`, otherwise the selected external
 * pack is loaded from the resolved pack directory.
 *
 * # Safety
 *
 * `config` must be a valid live TypeClaw host-config pointer.
 */
TcEngine *typeclaw_engine_new_from_host_config(const TcHostConfig *config);

TcHostConfig *typeclaw_host_config_load(void);

TcHostConfig *typeclaw_host_config_load_defaults(void);

/**
 * Loads host config from caller-supplied environment values.
 *
 * Null pointers mean "unset". This exists so hosts/tests can validate config
 * precedence without reimplementing config parsing outside Rust.
 *
 * # Safety
 *
 * Each non-null pointer must be a valid NUL-terminated UTF-8 C string that
 * remains alive for the duration of this call.
 */
TcHostConfig *typeclaw_host_config_load_with_environment(const char *config_path_utf8,
                                                         const char *home_utf8,
                                                         const char *data_dir_utf8,
                                                         const char *pack_dir_utf8);

/**
 * Frees host config allocated by TypeClaw.
 *
 * # Safety
 *
 * `config` must be null or a pointer returned by a TypeClaw host-config
 * constructor that has not already been freed.
 */
void typeclaw_host_config_free(TcHostConfig *config);

/**
 * Writes the resolved engine config into `out_config`.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 * `out_config` must be null or point to writable memory for one `TcEngineConfig`.
 */
void typeclaw_host_config_engine_config(const TcHostConfig *config, TcEngineConfig *out_config);

/**
 * Returns the config file path, or null when defaults were used.
 *
 * The returned pointer is owned by `config` and remains valid until `config`
 * is freed.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_source_path(const TcHostConfig *config);

/**
 * Returns the normalized secondary language id.
 *
 * The returned pointer is owned by `config` and remains valid until `config`
 * is freed.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_secondary_language(const TcHostConfig *config);

/**
 * Returns the resolved pack directory, or null when none could be resolved.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_pack_directory(const TcHostConfig *config);

/**
 * Returns the resolved data directory, or null when none is configured.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_data_directory(const TcHostConfig *config);

/**
 * Returns `embedded`, `data_dir`, or `pack:<id>`.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_engine_source(const TcHostConfig *config);

/**
 * Returns the configured macOS English input-source id, or null when unset.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_macos_english_input_source_id(const TcHostConfig *config);

/**
 * Returns the configured macOS secondary input-source id, or null when unset.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
const char *typeclaw_host_config_macos_secondary_input_source_id(const TcHostConfig *config);

/**
 * Returns 1 when `bundle_id_utf8` is fully disabled.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 * `bundle_id_utf8` must be null or a valid NUL-terminated UTF-8 string.
 */
uint8_t typeclaw_host_config_is_bundle_disabled(const TcHostConfig *config,
                                                const char *bundle_id_utf8);

/**
 * Returns 1 when automatic processing is disabled for `bundle_id_utf8`.
 *
 * Fully disabled bundles also disable automatic processing.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 * `bundle_id_utf8` must be null or a valid NUL-terminated UTF-8 string.
 */
uint8_t typeclaw_host_config_is_automatic_processing_disabled(const TcHostConfig *config,
                                                              const char *bundle_id_utf8);

/**
 * Returns the number of fully disabled bundle IDs.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
size_t typeclaw_host_config_disabled_bundle_count(const TcHostConfig *config);

/**
 * Returns the number of bundle IDs with automatic processing disabled.
 *
 * This count does not include fully disabled bundle IDs; use
 * `typeclaw_host_config_disabled_bundle_count` for that list.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer.
 */
size_t typeclaw_host_config_auto_disabled_bundle_count(const TcHostConfig *config);

/**
 * Resolves host-surface facts into TypeClaw input policy.
 *
 * Rust owns the policy decision; hosts only provide facts about the current
 * macOS surface.
 *
 * # Safety
 *
 * `config` must be null or a valid live TypeClaw host-config pointer. Every
 * non-null pointer inside `facts` must point to a valid NUL-terminated UTF-8
 * string that remains alive for this call. `out_policy` must be null or point
 * to writable memory for one `TcHostInputPolicy`.
 */
void typeclaw_host_config_resolve_input_policy(const TcHostConfig *config,
                                               TcHostSurfaceFacts facts,
                                               TcHostInputPolicy *out_policy);

/**
 * Frees an engine pointer created by `typeclaw_engine_new_embedded` or
 * `typeclaw_engine_new_from_data_dir` / `typeclaw_engine_new_from_pack_dir`.
 *
 * Passing any other pointer is undefined behavior.
 *
 * # Safety
 *
 * `engine` must be null or a pointer returned by any TypeClaw constructor
 * (`typeclaw_engine_new_embedded`, `typeclaw_engine_new_from_data_dir`,
 * `typeclaw_engine_new_from_pack_dir`) that has not already been freed.
 * After this call, the pointer must not be used again.
 */
void typeclaw_engine_free(TcEngine *engine);

/**
 * Clears the current token buffer without changing the active layout.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
void typeclaw_engine_reset_token(TcEngine *engine);

/**
 * Resets both the active layout and the current token. Use when the host
 * detects an out-of-band layout change (Cmd+Space, manual switch, etc.) and
 * needs to re-sync the engine state.
 *
 * `layout` must be one of `TC_LAYOUT_ENGLISH` or `TC_LAYOUT_SECONDARY`;
 * any other value is ignored.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by a TypeClaw constructor.
 */
void typeclaw_engine_reset_layout(TcEngine *engine, uint8_t layout);

/**
 * Sets host-level bypass context.
 *
 * `TC_CONTEXT_SECURE_INPUT` means a password/secure field is active.
 * `TC_CONTEXT_AUTOMATIC_PROCESSING_DISABLED` means automatic processing is
 * disabled for the foreground app.
 * `TC_CONTEXT_AUTOMATIC_SWITCHING_DISABLED` means automatic layout switches
 * are disabled, but the engine still observes the current token.
 * Secure input and full automatic-processing disable return Keep/Bypass and
 * clear the token; automatic-switching disable keeps normal observation.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by a TypeClaw constructor.
 */
void typeclaw_engine_set_host_context(TcEngine *engine, uint32_t flags);

/**
 * Forces the current token to the opposite side of the active language pair.
 *
 * When a token is active, this captures a pending replacement snapshot before
 * resetting the token. The host can consume that snapshot with
 * `typeclaw_engine_take_pending_replacement_utf8`.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by `typeclaw_engine_new_embedded` or
 * any other TypeClaw constructor. `out_observation` must point to writable memory for one
 * `TcObservation`.
 */
void typeclaw_engine_force_switch_layout(TcEngine *engine, TcObservation *out_observation);

/**
 * Returns the engine's current inferred layout.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
uint8_t typeclaw_engine_current_layout(TcEngine *engine);

/**
 * Returns the engine's current tracked token length.
 *
 * This is the number of logical token characters currently tracked by the
 * engine, not a byte count.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
size_t typeclaw_engine_token_len(TcEngine *engine);

/**
 * Returns the character count to delete for the pending replacement captured
 * by the last `TC_OBSERVATION_SWITCH_FUTURE_LAYOUT` action.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
size_t typeclaw_engine_pending_replacement_delete_count(TcEngine *engine);

/**
 * Returns the UTF-8 byte length of the pending replacement text, excluding a
 * trailing NUL.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
size_t typeclaw_engine_pending_replacement_utf8_len(TcEngine *engine);

/**
 * Returns the UTF-8 byte length of the inverse pending replacement text,
 * excluding a trailing NUL.
 *
 * This is the text currently represented by the active token before the
 * pending replacement is applied. Hosts can keep it to toggle a manual
 * replacement back without reading text from the foreground app.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw constructor.
 */
size_t typeclaw_engine_pending_replacement_inverse_utf8_len(TcEngine *engine);

/**
 * Copies the inverse pending replacement text as a NUL-terminated UTF-8 string.
 *
 * Returns the full required byte length, excluding the trailing NUL. If
 * `out_utf8_capacity` is too small, the written string is truncated but still
 * NUL-terminated when capacity is non-zero. Copying does not clear the pending
 * replacement.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw
 * constructor. `out_utf8` must be null or point to writable memory for
 * `out_utf8_capacity` bytes.
 */
size_t typeclaw_engine_copy_pending_replacement_inverse_utf8(TcEngine *engine,
                                                             char *out_utf8,
                                                             size_t out_utf8_capacity);

/**
 * Takes the pending replacement text as a NUL-terminated UTF-8 string.
 *
 * Returns the full required byte length, excluding the trailing NUL. If
 * `out_utf8_capacity` is too small, the written string is truncated but still
 * NUL-terminated when capacity is non-zero. Taking the replacement clears it.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any TypeClaw
 * constructor. `out_utf8` must be null or point to writable memory for
 * `out_utf8_capacity` bytes.
 */
size_t typeclaw_engine_take_pending_replacement_utf8(TcEngine *engine,
                                                     char *out_utf8,
                                                     size_t out_utf8_capacity);

/**
 * Observes a single input event and writes the resulting state notification.
 *
 * `engine` and `out_observation` must be non-null and valid. `out_observation`
 * is fully overwritten.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by any TypeClaw constructor.
 * `out_observation` must point to writable memory for one `TcObservation`.
 */
void typeclaw_engine_observe(TcEngine *engine, TcEvent event, TcObservation *out_observation);

/**
 * Writes the default runtime config into `out_config`.
 *
 * # Safety
 *
 * `out_config` must be null or point to writable memory for one `TcEngineConfig`.
 */
void typeclaw_engine_default_config(TcEngineConfig *out_config);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TYPECLAW_H */
