/* Generated by cbindgen. Do not edit by hand. */

#ifndef TYPEFLOW_H
#define TYPEFLOW_H

#include <stdint.h>
#include <stddef.h>

#define TF_EVENT_LETTER 0

#define TF_EVENT_BACKSPACE 1

#define TF_EVENT_END_TOKEN 2

#define TF_EVENT_LITERAL 3

#define TF_MOD_SHIFT 1

#define TF_MOD_CONTROL 2

#define TF_MOD_OPTION 4

#define TF_MOD_COMMAND 8

#define TF_CONTEXT_SECURE_INPUT 1

#define TF_CONTEXT_AUTOMATIC_PROCESSING_DISABLED 2

#define TF_CONTEXT_AUTOMATIC_SWITCHING_DISABLED 4

#define TF_HOST_POLICY_SECURE_INPUT 1

#define TF_HOST_POLICY_AUTOMATIC_PROCESSING_DISABLED 2

#define TF_HOST_POLICY_MANUAL_CONVERSION_DISABLED 4

#define TF_HOST_POLICY_TERMINAL_SURFACE 8

#define TF_HOST_POLICY_REASON_NORMAL 0

#define TF_HOST_POLICY_REASON_SECURE_INPUT 1

#define TF_HOST_POLICY_REASON_TERMINAL_BUNDLE 2

#define TF_HOST_POLICY_REASON_TERMINAL_SURFACE 3

#define TF_HOST_POLICY_REASON_DISABLED_BUNDLE 4

#define TF_HOST_POLICY_REASON_AUTOMATIC_PROCESSING_DISABLED_BUNDLE 5

#define TF_HOST_POLICY_REASON_UNAVAILABLE_HOST_CONFIG 255

#define TF_ACTION_KEEP 0

#define TF_ACTION_COMMIT 1

#define TF_ACTION_REPLACE 2

#define TF_ACTION_RESET 3

#define TF_LAYOUT_ENGLISH 0

#define TF_LAYOUT_SECONDARY 1

#define TF_REPLACE_BUF_LEN 4096

typedef struct TfEngine TfEngine;

typedef struct TfHostConfig TfHostConfig;

typedef struct {
    size_t min_token_len;
    size_t max_token_len;
    float confidence_margin;
    float dict_exact_weight;
    float dict_prefix_weight;
    float ngram_only_confidence_margin;
    float bigram_weight;
    float trigram_weight;
    uint8_t length_normalize;
    uint8_t disable_on_internal_caps;
} TfEngineConfig;

typedef struct {
    uint8_t secure_input;
    const char *bundle_id_utf8;
    const char *application_name_utf8;
    const char *input_client_class_utf8;
    const char *focused_element_role_utf8;
    const char *focused_element_subrole_utf8;
    const char *focused_element_role_description_utf8;
    const char *focused_element_identifier_utf8;
    const char *focused_element_description_utf8;
    const char *focused_window_title_utf8;
} TfHostSurfaceFacts;

typedef struct {
    uint32_t flags;
    uint8_t reason;
} TfHostInputPolicy;

typedef struct {
    uint8_t tag;
    uint32_t commit_codepoint;
    size_t replace_old_len;
    size_t replace_text_len;
    uint8_t replace_layout;
    uint8_t replace_text[TF_REPLACE_BUF_LEN];
} TfAction;

typedef struct {
    uint8_t tag;
    uint8_t physical;
    uint8_t modifiers;
    uint32_t codepoint;
} TfEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *typeflow_last_error_message(void);

/**
 * Allocates a new engine using the language bundle embedded into the library.
 *
 * This is the normal constructor for release builds and the future macOS input method.
 * Returns null if the embedded bundle fails to deserialize.
 */
TfEngine *typeflow_engine_new_embedded(void);

/**
 * Allocates a new embedded engine with explicit runtime tuning.
 *
 * Returns null if the embedded bundle fails to deserialize or the config contains
 * invalid numeric values.
 */
TfEngine *typeflow_engine_new_embedded_with_config(TfEngineConfig config);

/**
 * Allocates a new engine, loading the language bundle from the directory at `data_dir_utf8`.
 * `data_dir_utf8` must point to a NUL-terminated UTF-8 path. Returns null on failure.
 *
 * # Safety
 *
 * `data_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TfEngine *typeflow_engine_new_from_data_dir(const char *data_dir_utf8);

/**
 * Allocates a new engine from `data_dir_utf8` with explicit runtime tuning.
 *
 * Returns null if path decoding, data loading, or config validation fails.
 *
 * # Safety
 *
 * `data_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TfEngine *typeflow_engine_new_from_data_dir_with_config(const char *data_dir_utf8,
                                                        TfEngineConfig config);

/**
 * Allocates a new engine using embedded English plus the secondary pack in `pack_dir_utf8`.
 * The pack directory must contain `pack.toml`, `ngrams.bin`, and `dict.fst`.
 *
 * # Safety
 *
 * `pack_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TfEngine *typeflow_engine_new_from_pack_dir(const char *pack_dir_utf8);

/**
 * Allocates a new engine from `pack_dir_utf8` with explicit runtime tuning.
 *
 * Returns null if path decoding, pack loading, or config validation fails.
 *
 * # Safety
 *
 * `pack_dir_utf8` must be either null or a valid pointer to a NUL-terminated UTF-8 C string
 * that remains alive for the duration of this call.
 */
TfEngine *typeflow_engine_new_from_pack_dir_with_config(const char *pack_dir_utf8,
                                                        TfEngineConfig config);

/**
 * Allocates a new engine from a resolved host config.
 *
 * Rust owns the engine-source decision: data directory wins, embedded
 * Ukrainian is used for `secondary = "uk"`, otherwise the selected external
 * pack is loaded from the resolved pack directory.
 *
 * # Safety
 *
 * `config` must be a valid live Typeflow host-config pointer.
 */
TfEngine *typeflow_engine_new_from_host_config(const TfHostConfig *config);

TfHostConfig *typeflow_host_config_load(void);

TfHostConfig *typeflow_host_config_load_defaults(void);

/**
 * Loads host config from caller-supplied environment values.
 *
 * Null pointers mean "unset". This exists so hosts/tests can validate config
 * precedence without reimplementing config parsing outside Rust.
 *
 * # Safety
 *
 * Each non-null pointer must be a valid NUL-terminated UTF-8 C string that
 * remains alive for the duration of this call.
 */
TfHostConfig *typeflow_host_config_load_with_environment(const char *config_path_utf8,
                                                         const char *home_utf8,
                                                         const char *data_dir_utf8,
                                                         const char *pack_dir_utf8);

/**
 * Frees host config allocated by Typeflow.
 *
 * # Safety
 *
 * `config` must be null or a pointer returned by a Typeflow host-config
 * constructor that has not already been freed.
 */
void typeflow_host_config_free(TfHostConfig *config);

/**
 * Writes the resolved engine config into `out_config`.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 * `out_config` must be null or point to writable memory for one `TfEngineConfig`.
 */
void typeflow_host_config_engine_config(const TfHostConfig *config, TfEngineConfig *out_config);

/**
 * Returns the config file path, or null when defaults were used.
 *
 * The returned pointer is owned by `config` and remains valid until `config`
 * is freed.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
const char *typeflow_host_config_source_path(const TfHostConfig *config);

/**
 * Returns the normalized secondary language id.
 *
 * The returned pointer is owned by `config` and remains valid until `config`
 * is freed.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
const char *typeflow_host_config_secondary_language(const TfHostConfig *config);

/**
 * Returns the resolved pack directory, or null when none could be resolved.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
const char *typeflow_host_config_pack_directory(const TfHostConfig *config);

/**
 * Returns the resolved data directory, or null when none is configured.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
const char *typeflow_host_config_data_directory(const TfHostConfig *config);

/**
 * Returns `embedded`, `data_dir`, or `pack:<id>`.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
const char *typeflow_host_config_engine_source(const TfHostConfig *config);

/**
 * Returns 1 when `bundle_id_utf8` is fully disabled.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 * `bundle_id_utf8` must be null or a valid NUL-terminated UTF-8 string.
 */
uint8_t typeflow_host_config_is_bundle_disabled(const TfHostConfig *config,
                                                const char *bundle_id_utf8);

/**
 * Returns 1 when automatic processing is disabled for `bundle_id_utf8`.
 *
 * Fully disabled bundles also disable automatic processing.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 * `bundle_id_utf8` must be null or a valid NUL-terminated UTF-8 string.
 */
uint8_t typeflow_host_config_is_automatic_processing_disabled(const TfHostConfig *config,
                                                              const char *bundle_id_utf8);

/**
 * Returns the number of fully disabled bundle IDs.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
size_t typeflow_host_config_disabled_bundle_count(const TfHostConfig *config);

/**
 * Returns the number of bundle IDs with automatic processing disabled.
 *
 * This count does not include fully disabled bundle IDs; use
 * `typeflow_host_config_disabled_bundle_count` for that list.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer.
 */
size_t typeflow_host_config_auto_disabled_bundle_count(const TfHostConfig *config);

/**
 * Resolves host-surface facts into Typeflow input policy.
 *
 * Rust owns the policy decision; hosts only provide facts about the current
 * macOS surface.
 *
 * # Safety
 *
 * `config` must be null or a valid live Typeflow host-config pointer. Every
 * non-null pointer inside `facts` must point to a valid NUL-terminated UTF-8
 * string that remains alive for this call. `out_policy` must be null or point
 * to writable memory for one `TfHostInputPolicy`.
 */
void typeflow_host_config_resolve_input_policy(const TfHostConfig *config,
                                               TfHostSurfaceFacts facts,
                                               TfHostInputPolicy *out_policy);

/**
 * Frees an engine pointer created by `typeflow_engine_new_embedded` or
 * `typeflow_engine_new_from_data_dir` / `typeflow_engine_new_from_pack_dir`.
 *
 * Passing any other pointer is undefined behavior.
 *
 * # Safety
 *
 * `engine` must be null or a pointer returned by any Typeflow constructor
 * (`typeflow_engine_new_embedded`, `typeflow_engine_new_from_data_dir`,
 * `typeflow_engine_new_from_pack_dir`) that has not already been freed.
 * After this call, the pointer must not be used again.
 */
void typeflow_engine_free(TfEngine *engine);

/**
 * Clears the current token buffer without changing the active layout.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any Typeflow constructor.
 */
void typeflow_engine_reset_token(TfEngine *engine);

/**
 * Resets both the active layout and the current token. Use when the host
 * detects an out-of-band layout change (Cmd+Space, manual switch, etc.) and
 * needs to re-sync the engine state.
 *
 * `layout` must be one of `TF_LAYOUT_ENGLISH` or `TF_LAYOUT_SECONDARY`;
 * any other value is ignored.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by a Typeflow constructor.
 */
void typeflow_engine_reset_layout(TfEngine *engine, uint8_t layout);

/**
 * Sets host-level bypass context.
 *
 * `TF_CONTEXT_SECURE_INPUT` means a password/secure field is active.
 * `TF_CONTEXT_AUTOMATIC_PROCESSING_DISABLED` means automatic processing is
 * disabled for the foreground app.
 * `TF_CONTEXT_AUTOMATIC_SWITCHING_DISABLED` means automatic layout switches
 * are disabled, but the engine still commits keys in the current layout.
 * Secure input and full automatic-processing disable return Keep/Bypass and
 * clear the token; automatic-switching disable keeps normal commit behavior.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by a Typeflow constructor.
 */
void typeflow_engine_set_host_context(TfEngine *engine, uint32_t flags);

/**
 * Forces the current token to the opposite side of the active language pair.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by `typeflow_engine_new_embedded` or
 * any other Typeflow constructor. `out_action` must point to writable memory for one `TfAction`.
 */
void typeflow_engine_force_switch_token(TfEngine *engine, TfAction *out_action);

/**
 * Converts the visible token supplied by the host to the opposite keyboard side.
 *
 * This is for hosts whose text controls do not keep IME token tracking stable
 * across selection/delete/replacement operations. The input must be a
 * null-terminated UTF-8 string. On success, the engine layout is reset to the
 * replacement side and `out_action` receives a `ReplaceToken` action whose
 * `old_len` is the input token's character count.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by a Typeflow constructor.
 * `token_utf8` must point to a null-terminated UTF-8 string. `out_action` must
 * point to writable memory for one `TfAction`.
 */
void typeflow_engine_convert_visible_token(TfEngine *engine,
                                           const char *token_utf8,
                                           TfAction *out_action);

/**
 * Converts the trailing visible token inside the host-supplied text tail.
 *
 * The host should pass a bounded slice of committed text immediately before
 * the caret. Rust owns the token grammar, including punctuation-position keys
 * that are letters in the active secondary layout.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by a Typeflow constructor.
 * `visible_tail_utf8` must point to a null-terminated UTF-8 string.
 * `out_action` must point to writable memory for one `TfAction`.
 */
void typeflow_engine_convert_visible_tail(TfEngine *engine,
                                          const char *visible_tail_utf8,
                                          TfAction *out_action);

/**
 * Rebuilds a replacement action from the host's visible committed token prefix
 * plus the current physical key.
 *
 * This keeps replacement ranges correct in text controls that report unstable
 * selection/caret state to IMK. `visible_prefix_utf8` is the host text before
 * the current key; the returned action replaces exactly that prefix with the
 * full rendered token for `target_layout`.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by a Typeflow constructor.
 * `visible_prefix_utf8` must point to a null-terminated UTF-8 string.
 * `out_action` must point to writable memory for one `TfAction`.
 */
void typeflow_engine_replace_visible_prefix_with_key(TfEngine *engine,
                                                     const char *visible_prefix_utf8,
                                                     uint8_t physical,
                                                     uint8_t modifiers,
                                                     uint8_t target_layout,
                                                     TfAction *out_action);

/**
 * Rebuilds a replacement action from a bounded host-visible text tail plus the
 * current physical key.
 *
 * Rust extracts the trailing token from `visible_tail_utf8` using the loaded
 * keyboard maps, then returns a `ReplaceToken` action whose `old_len` targets
 * exactly that trailing token.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by a Typeflow constructor.
 * `visible_tail_utf8` must point to a null-terminated UTF-8 string.
 * `out_action` must point to writable memory for one `TfAction`.
 */
void typeflow_engine_replace_visible_tail_with_key(TfEngine *engine,
                                                   const char *visible_tail_utf8,
                                                   uint8_t physical,
                                                   uint8_t modifiers,
                                                   uint8_t target_layout,
                                                   TfAction *out_action);

/**
 * Returns the engine's current inferred layout.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any Typeflow constructor.
 */
uint8_t typeflow_engine_current_layout(TfEngine *engine);

/**
 * Returns the engine's current tracked token length.
 *
 * This is the number of logical token characters currently tracked by the
 * engine, not a byte count. It is intended for hosts that maintain a small
 * mirror of committed token text to avoid expensive host text reads.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any Typeflow constructor.
 */
size_t typeflow_engine_token_len(TfEngine *engine);

/**
 * Writes the current rendered token as a replacement action.
 *
 * This lets hosts using marked text redraw the whole active composition after
 * non-inserting token operations such as backspace. The returned replacement
 * length is the current logical token length.
 *
 * # Safety
 *
 * `engine` must be null or a valid live pointer returned by any Typeflow
 * constructor. `out_action` must be null or point to writable memory for one
 * `TfAction`.
 */
void typeflow_engine_current_token(TfEngine *engine, TfAction *out_action);

/**
 * Processes a single input event and writes the resulting action into `out_action`.
 *
 * `engine` and `out_action` must be non-null and valid. `out_action` is fully overwritten.
 *
 * # Safety
 *
 * `engine` must be a valid live pointer returned by any Typeflow constructor.
 * `out_action` must point to writable memory for one `TfAction`.
 */
void typeflow_engine_process(TfEngine *engine, TfEvent event, TfAction *out_action);

/**
 * Writes the default runtime config into `out_config`.
 *
 * # Safety
 *
 * `out_config` must be null or point to writable memory for one `TfEngineConfig`.
 */
void typeflow_engine_default_config(TfEngineConfig *out_config);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TYPEFLOW_H */
